catalog/urls.py
from django.urls import path
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed-books', views.BorrowedBooksListView.as_view(), name='borrowed-books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

# edit author 
urlpatterns += [
    path('author/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.db.models.constraints import UniqueConstraint
from django.db.models.functions import Lower
import uuid
from django.conf import settings
from datetime import date

# Create your models here.

class Genre(models.Model):
    """ Model representing a book genre. """
    name = models.CharField(max_length=50, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', unique=True)
    
    def __str__(self) -> str:
        """ string for representing the Genre object. """
        return self.name
    
    def get_absolute_url(self):
        return reverse("genre-detail", kwargs={"id": self.id})
    
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message = "Genre already exists (case insensitive match)"
            ),
        ]
        
        
class Language(models.Model):
    """ Model representing a Language (e.g. English, French, Japanese, etc.) """
    name = models.CharField(max_length=50, help_text='Enter the book\'s natural language (e.g. English, French, Japanese etc.)', unique=True)
    
    def __str__(self) -> str:
        """ string for representing the Language object. """
        return self.name
    
    def get_absolute_url(self):
        return reverse("language-detail", kwargs={"id": self.id})
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message = "Language already exists (case insensitive match)"
            ),
        ]
        
class Book(models.Model):
    """ Model representing a book (but not a specific copy of a book). """
    title = models.CharField(max_length=200, help_text='Enter the title of the book')
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    genre = models.ManyToManyField('Genre', help_text='Select a genre for this book')
    
    language = models.ForeignKey('Language', on_delete=models.RESTRICT, null=True) #one to many relationship with Language
    
    
    def __str__(self) -> str:
        """ string for representing the Book object. """
        return self.title
    
    def get_absolute_url(self):
        """ Returns the url to access a detail record for this book. """
        return reverse("book-detail", kwargs={"pk": self.pk})
    
    
class BookInstance(models.Model):
    """ Model representing a specific copy of a book (i.e. that can be borrowed from the library). """ 
    guid = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )   
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    def __str__(self) -> str:
        """ string for representing the Model object. """
        return f'{self.guid} ({self.book.title})'
    
    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)
    
class Author(models.Model):
    """ Model representing an author. """
    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(null=True, blank=True)
    
    def __str__(self) -> str:
        """ string for representing the Model object. """
        return f'{self.last_name}, {self.first_name}'
    
    def get_absolute_url(self):
        """ Returns the url to access a particular author instance. """
        return reverse("author-detail", kwargs={"pk": self.pk})
    
    class Meta:
        ordering = ['last_name', 'first_name']

catalog/forms.py
from django import forms

import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        
        if data > datetime.date.today() + datetime.timedelta(weeks = 4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))
        
        return data

catalog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre, Language

from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import RenewBookForm
from django.urls import reverse, reverse_lazy
import datetime


from django.contrib.auth.mixins import AccessMixin

class StaffRequiredMixin(AccessMixin):
    """
    Mixin that requires the user to be a staff member.
    """
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            # Optionally, redirect to a custom page or return a 403 response
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)
    
    def handle_no_permission(self):
        return HttpResponseForbidden("You do not have permission to access this page.")


# Create your views here.
@login_required
def index(request):
    
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    num_authors = Author.objects.count()
    num_genre = Genre.objects.count()
    num_books_with_word_power = Book.objects.filter(title__icontains= 'power').count()
    
    num_visits = request.session.get('num_visits', 0)
    num_visits += 1
    request.session['num_visits'] = num_visits
    
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genre': num_genre,
        'num_books_with_word_power': num_books_with_word_power,
        'num_visits': num_visits
    }
    
    return render(request, 'index.html', context=context)
    
    
class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    template_name = 'catalog/books.html'
    queryset = Book.objects.all()[:5]
    context_object_name = 'books'
    paginate_by = 2
    
class BookDetailView(generic.DetailView):
    model = Book
    
    
class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    template_name = 'catalog/authors.html'
    queryset = Author.objects.all()
    context_object_name = 'authors'
    paginate_by = 2

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'
    
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 2
    context_object_name = 'bookinstances'
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
class BorrowedBooksListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/borrowed_books.html'
    context_object_name = 'borrowed_books'
    paginate_by = 5
    
    permission_required = 'catalog.can_mark_returned'
    
    
    def get_queryset(self) -> QuerySet[Any]:
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')
    
@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = BookInstance.objects.get(pk=pk)
    
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return HttpResponseRedirect(reverse('borrowed-books'))
        
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial = {'renewal_date': proposed_renewal_date})
        
        
    context = {
        'form': form,
        'book_instance': book_instance
    }
    
    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreateView(PermissionRequiredMixin, generic.CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth']
    initial = {'date_of_birth': '05/01/2018'}
    permission_required = 'catalog.add_author'
    
    
class AuthorUpdateView(PermissionRequiredMixin, generic.UpdateView):
    model = Author
    fields = '__all__'
    permission_required = 'catalog.change_author'
    
class AuthorDeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    
    permission_required = 'catalog.delete_author'
    
    def form_valid(self, form):
        try :
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        
        except Exception as e:
            return HttpResponseRedirect(reverse('author-detail', kwargs={'pk': self.object.pk}))
            
    

catalog/templates/catalog/author_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Delete Author: {{ author }}</h1>
{% if author.book_set.all %}

<p>You can't delete this author until all their books have been deleted:</p>
<ul>
  {% for book in author.book_set.all %}
    <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the author?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author: {{ author }}</h1>
    
    <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>    
    <h2>Books</h2>
    <ul>
        {% for book in author.book_set.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}


{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_author or perms.catalog.delete_author %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_author %}
      <li><a href="{% url 'author-update' author.id %}">Update author</a></li>
    {% endif %}
    {% if not author.book_set.all and perms.catalog.delete_author %}
      <li><a href="{% url 'author-delete' author.id %}">Delete author</a></li>
    {% endif %}
    </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form action='' method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type='submit' value='Submit'>
</form>

{% endblock %}

catalog/templates/catalog/authors.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Authors</h1>
    {% if authors %}
        <ul>
            {% for author in authors %}
            <li>
                <a href="{{ author.get_absolute_url }}">{{ author }}</a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Borrowed Book List</h1>
{% if bookinstances %}
    <ul> 
        {% for bookinstance in bookinstances %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}"><a href="{% url 'book-detail' bookinstance.book.pk  %}">{{ bookinstance.book.title }}</a> ({{ bookinstance.due_back }})</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books borrowed.</p>
{% endif %}


{% endblock %}

catalog/templates/catalog/books.html
{% extends "base_generic.html" %}


{% block content %}
<h1>Book List</h1>
{% if books %}
  <ul>
    {% for book in books %}
    <li>
      <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
      ({{book.author}})
    </li>
    {% endfor %}
  </ul>
{% else %}
  <p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/borrowed_books.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Borrowed Book List</h1>
{% if perms.catalog.can_mark_returned %}
    {% if borrowed_books %}
        <ul> 
            {% for bookinstance in borrowed_books %}
                <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}"><a href="{% url 'book-detail' bookinstance.book.pk  %}">{{ bookinstance.book.title }}</a> ({{ bookinstance.due_back }})  ({{ bookinstance.borrower }})  {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinstance.guid %}">Renew</a>{% endif %}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books borrowed.</p>
    {% endif %}

{% else %}
    <p>You are not authorized to view this page.</p>
{% endif %}

{% endblock %}